---
abstract: 'word expander by associatives'
author:
  - 'Takeshi Miki <miki@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.97'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-JA-Expand
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  LWP::UserAgent: 0
  Lingua::JA::TFIDF: 0
  Test::More: 0
  UNIVERSAL::require: 0
  XML::LibXML::Simple: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01002
