--- 
abstract: word expander by associatives
author: 
  - Takeshi Miki <miki@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Lingua-JA-Expand
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  LWP::UserAgent: 0
  List::MoreUtils: 0
  UNIVERSAL::require: 0
  XML::TreePP: 0
tests: t/*.t t/*/*.t
version: 0.00001
